unpackaged/main/default/objects/Account/fields/Legacy_SalesforceID__c.field-meta.xml
<CustomField>
    <fullName>Legacy_SalesforceID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Legacy SalesforceID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/AssignRenewalOpptoCustomerService__c/AssignRenewalOpptoCustomerService__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Assign Renewal Opp to Customer Service</label>
</CustomObject>

unpackaged/main/default/objects/AssignRenewalOpptoCustomerService__c/fields/Renewal_Assignee__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Assignee__c</fullName>
    <label>Renewal Assignee</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Legacy_SalesforceID__c.field-meta.xml
<CustomField>
    <fullName>Legacy_SalesforceID__c</fullName>
    <externalId>true</externalId>
    <label>Legacy SalesforceID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Recapture</fullName>
            </value>
            <value>
                <fullName>Repeat Business</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Renewal Upgrade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <inlineHelpText>Expiration Date of current Subscription.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Legacy_SalesforceID__c.field-meta.xml
<CustomField>
    <fullName>Legacy_SalesforceID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Legacy SalesforceID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Origination__c.field-meta.xml
<CustomField>
    <fullName>Origination__c</fullName>
    <description>Where the transaction came from.</description>
    <label>Origination</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cvent</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
                <default>true</default>
                <label>Website</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Renewal_Rate__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Rate__c</fullName>
    <label>Renewal Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Subscriptions_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Subscriptions_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Subscriptions</businessProcess>
    <label>Subscription Opportunity</label>
</RecordType>

unpackaged/main/default/objects/OpportunityLineItem/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Renewal_Rate__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Rate__c</fullName>
    <label>Renewal Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>.Subscription generated when Opportunity is Closed Won.</inlineHelpText>
    <label>Subscription</label>
    <referenceTo>Subscription_NEW__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Duration_Days__c.field-meta.xml
<CustomField>
    <fullName>Duration_Days__c</fullName>
    <label>Duration (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Legacy_SalesforceID__c.field-meta.xml
<CustomField>
    <fullName>Legacy_SalesforceID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Legacy SalesforceID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Max_Users__c.field-meta.xml
<CustomField>
    <fullName>Max_Users__c</fullName>
    <label>Max. Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Subscription.recordType-meta.xml
<RecordType>
    <fullName>Subscription</fullName>
    <active>true</active>
    <description>Subscription based Products</description>
    <label>Subscription</label>
</RecordType>

unpackaged/main/default/objects/Quote/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

unpackaged/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>A subscription to an edition of a publication.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>S-{000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Owner of this Subscription</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Subscription__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <defaultValue>Today()+365</defaultValue>
    <description>Date this subscription expires</description>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Subscription__c/fields/Renewal_Rate__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Rate at which this subscription renews</description>
    <label>Renewal Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/Subscription_NEW__c.object-meta.xml
<CustomObject>
    <label>Subscription (NEW)</label>
    <nameField>
        <displayFormat>Sub-{0000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions (NEW)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions (NEW)</relationshipLabel>
    <relationshipName>Subscriptions_NEW</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Renewal_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A renewal Opportunity is created 90 days before this subscription expires. If upgraded mid-term via the button above, the upgrade Opportunity created is referenced here.</inlineHelpText>
    <label>Renewal/Upgrade Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Subscriptions (NEW)</relationshipLabel>
    <relationshipName>Subscriptions_NEW</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Renewal_Rate__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Rate__c</fullName>
    <label>Renewal Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Multi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchCloneOpportunity.cls
/**
 * Class to clone opportunity with product automatically 90 days before a Subscription Expiration Date.
 * Create Date : 02/01/2013
 */
global class BatchCloneOpportunity implements Database.Batchable<sObject>{
    public static final String TYPE_SINGLE = 'Single';
    public static final String RENEWAL_TYPE = 'Renewal';
    public static final String STAGE_PROPOSAL = 'Proposal/Price Quote';
    public static final String SUBSCRIPTIONRECORDTYPE = 'Subscriptions_Opportunity';
    public static final String OPP_TYPE = 'Subscription';
    public String id ; 
    public Boolean isButton = false; 
    
    public BatchCloneOpportunity(String id, Boolean isButton){
        this.id = id;
        this.isButton = isButton;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        Date next90Day = System.today().addDays(90);
        String CheckDate = ' =: next90Day';
        if(isButton) CheckDate = ' = NEXT_90_DAYS';
        return Database.getQueryLocator('Select ListPrice , Renewal_Rate__c,Contact__c,PricebookEntryId,Legacy_SalesforceID__c,Quantity,Expiry_Date__c, Description, ServiceDate, '+
            'Subscription__r.Type__c, Subscription__r.Name , Subscription__r.Renewal_Opportunity__c, Subscription__r.Expiration_Date__c, Subscription__r.Start_Date__c, '+
            'Subscription__r.Renewal_Opportunity__r.Business_Type__c,Subscription__r.Renewal_Rate__c, PricebookEntry.Product2.Max_Users__c, PricebookEntry.Product2.Duration_Days__c, Subscription__c, OpportunityId '+
            'From OpportunityLineItem '+
            'Where Subscription__c!= null and Subscription__r.Expiration_Date__c != null and '+
            'Subscription__r.Expiration_Date__c '+CheckDate+' '+(!isEmpty(id)?'and OpportunityId =: id':''));
    }
    global void execute(Database.BatchableContext BC, List<sObject> scope)
    {
        Set<String> sOppID = new Set<String>();
        Map<String,Date> mapOppWithExpiredDate = new Map<String,Date>();
        List<OpportunityLineItem> lstOppLines = new List<OpportunityLineItem>();
        Map<String,String> mapOppSub = new Map<String,String>();
        Map<Id, OpportunityContactRole> mapOppConRol = new Map<Id, OpportunityContactRole>();

        for(Sobject s : scope){
            OpportunityLineItem oppLine = (OpportunityLineItem) s;
            //for avoid duplicate clone the same opportunity and opp line
            if(oppLine.Subscription__r.Renewal_Opportunity__c != null && oppLine.Subscription__r.Renewal_Opportunity__r.Business_Type__c == RENEWAL_TYPE) continue;
            sOppID.add(oppLine.OpportunityId);
            mapOppSub.put(oppLine.OpportunityId,oppLine.Subscription__r.Name);
            mapOppWithExpiredDate.put(oppLine.OpportunityId,oppLine.Subscription__r.Expiration_Date__c);
            lstOppLines.add(oppLine);
        }
        //clone Opportunity with business type = 'Renewal', close date = subscription expired date, 
        //opportunity name always update to "Current year + 'Renewal'" , and stage name = 'Proposal/Price Quote'
        RecordType recordType = [select id from RecordType where DeveloperName =: SUBSCRIPTIONRECORDTYPE];
        List<Opportunity> lstOpp = new List<Opportunity>();
        Map<String,Opportunity> mapOpp = new Map<String, Opportunity>();
        AssignRenewalOpptoCustomerService__c cs = AssignRenewalOpptoCustomerService__c.getValues('Assign Renewal to User ID');

        for(Opportunity opp : [select Account.Name, Owner.IsActive,OwnerId, Type,AccountId, RecordTypeId, Origination__c,Name,StageName,Business_Type__c,CloseDate, (select OpportunityId, ContactId, Role, IsPrimary from OpportunityContactRoles) from Opportunity where id IN: sOppID]){//Database.query(getCreatableFieldsSOQL('Opportunity','Id IN: sOppID',''))){//[Select * From Opportunity where Id IN: sOppId]
            Opportunity oppClone = opp.clone(false, true);
            //check for activ user
            oppClone.OwnerId            = cs == null ? oppClone.OwnerId : cs.get('Renewal_Assignee__c')+'';
            //--check to replace year in opp name--//
            oppClone.Name               = opp.Account.Name+' - '+mapOppSub.get(opp.Id)+' - '+System.today().year()+' Renewal'; 
            oppClone.StageName          = STAGE_PROPOSAL;
            oppClone.Business_Type__c   = RENEWAL_TYPE;
            oppClone.CloseDate          = mapOppWithExpiredDate.get(opp.Id);
            oppClone.RecordTypeId       = recordType.Id;
            oppClone.Type               = OPP_TYPE;
            lstOpp.add(oppClone);
            mapOpp.put(opp.Id, oppClone);
            mapOppConRol.putAll(opp.OpportunityContactRoles);
        }

        if(!lstOpp.isEmpty()) insert lstOpp;

        //clone opportunity contact role
        List<OpportunityContactRole> ocrToCreate = new List<OpportunityContactRole>();
        for (OpportunityContactRole ocr : mapOppConRol.values()) {
            if(!mapOpp.containsKey(ocr.OpportunityId)) continue;
            ocrToCreate.add(new OpportunityContactRole(ContactId=ocr.ContactId, OpportunityId=mapOpp.get(ocr.OpportunityId).Id, Role=ocr.Role, IsPrimary=ocr.IsPrimary));
        }
        if (!ocrToCreate.isEmpty()) insert ocrToCreate;

        //clone opportunity product
        List<OpportunityLineItem> lstOppLine = new List<OpportunityLineItem>();
        List<Subscription_NEW__c> lstSub = new List<Subscription_NEW__c>();
        Map<String,String> mapSubOpp = new Map<String,String>();

        for(OpportunityLineItem oppLine : lstOppLines){
            if(!mapOpp.containsKey(oppLine.OpportunityId)) continue;
            OpportunityLineItem oppLineClone = oppLine.clone(false, true);
            oppLineClone.OpportunityId       = mapOpp.get(oppLine.OpportunityId).Id; 
             //-- clone unitPrice from old product if subscription type is single else zero--//
            oppLineClone.UnitPrice           = (oppLine.Subscription__r.Type__c == TYPE_SINGLE && oppLine.Subscription__r.Renewal_Rate__c != null?oppLine.Subscription__r.Renewal_Rate__c:0);
            //--start date = subscription expiredate--//
            oppLineClone.ServiceDate         = oppLine.Subscription__r.Expiration_Date__c;
            //--expiredate = product duration + start date--//
            Integer dateDuration = (oppLine.PricebookEntry.Product2.Duration_Days__c != null ? Integer.valueOF(oppLine.PricebookEntry.Product2.Duration_Days__c) : 0);
            oppLineClone.Expiry_Date__c      = oppLine.Subscription__r.Expiration_Date__c + dateDuration;
            oppLineClone.Subscription__c     = null;
            lstOppLine.add(oppLineClone);
            //update The expiring subscription look up to the renewal opportunity.
            if(mapSubOpp.containsKey(oppLine.Subscription__c)) continue;
            mapSubOpp.put(oppLine.Subscription__c, oppLineClone.OpportunityId);
        }
        if(!lstOppLine.isEmpty()) insert lstOppLine;
        if(mapSubOpp != null && !mapSubOpp.isEmpty()){
            for(String subId : mapSubOpp.keySet()){
                 lstSub.add(new Subscription_NEW__c(id = subId , Renewal_Opportunity__c = mapSubOpp.get(subId)));
            }
        }
        if(!lstSub.isEmpty()) update lstSub;
    }

    global void finish(Database.BatchableContext BC){

    }
    
    /**
     * For testing only
     */
     
    public static final String QUEUED_STATUS='Queued'; 
    public static final String PROCESSING_STATUS='Processing';
    public static final String PREPARING_STATUS='Preparing';
    
    /**
     * Check is full batch in process
     */
    public static Boolean isFullBatchInProcess(){
        return 5 == [Select count() From AsyncApexJob a where Status=:QUEUED_STATUS OR Status=:PROCESSING_STATUS OR Status=:PREPARING_STATUS];
       
   }    
   
   /**
    * Check is current batch in process
    */
    public static Boolean isBatchInProcess(String className){
        List<AsyncApexJob> jobs = [Select a.Status,a.ApexClass.Name, a.MethodName, a.JobType, a.ApexClassId From AsyncApexJob a where Status=:QUEUED_STATUS OR Status=:PROCESSING_STATUS OR Status=:PREPARING_STATUS];
        for(AsyncApexJob job: jobs) {
            if(job.ApexClass.Name == className) return true;
        }
        return false;
   }
   
   /**
    * Check is empty string
    */
    public static Boolean isEmpty(String val) {
        return null == val || '' == val || '--None--'==val || 'null'==val;
    }
    
    /**
     * Webservice methode for testing
     */   
    webservice static Boolean cloneOpportunity(String id) {
        if(isFullBatchInProcess() || isBatchInProcess('BatchCloneOpportunity')) return false;
        Date next90Day = System.today().addDays(90);
        String query = 'Select ListPrice , Renewal_Rate__c,Contact__c,PricebookEntryId,Legacy_SalesforceID__c,Quantity,Expiry_Date__c, Description, ServiceDate, '+
                        'Subscription__r.Type__c, Subscription__r.Renewal_Opportunity__c, Subscription__r.Expiration_Date__c, Subscription__r.Start_Date__c, '+
                        'Subscription__r.Renewal_Rate__c, PricebookEntry.Product2.Max_Users__c, PricebookEntry.Product2.Duration_Days__c, Subscription__c, OpportunityId '+
                        'From OpportunityLineItem '+
                        'where Subscription__c!= null and Subscription__r.Expiration_Date__c != null and '+
                        'Subscription__r.Expiration_Date__c = NEXT_90_DAYS '+(!isEmpty(id)?'and OpportunityId =: id':'');
        List<OpportunityLineItem> oplines = Database.query(query);
        if(oplines.isEmpty()) return false;
        BatchCloneOpportunity batch = new BatchCloneOpportunity(id, true);
        database.executeBatch(batch);
        return true;
    }       
        
}