unpackaged/main/default/objects/Account/fields/Number_of_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Contacts__c</fullName>
    <description>Shows the number of Contacts associated with this Account.</description>
    <label>Number of Contacts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_of_Leads__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Leads__c</fullName>
    <description>Shows the number of Leads associated with this Account.</description>
    <label>Number of Leads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_of_Singles_Users__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Singles_Users__c</fullName>
    <description>Shows the number of Single Subscription users associated with this Account.</description>
    <label>Number of Singles Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Multi</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Member of Multi-User Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <inlineHelpText>Trial subscription Expiration date. User will be granted access upon conversion of this Lead.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Number_of_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Contacts__c</fullName>
    <formula>Account__r.Number_of_Contacts__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Contacts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Number_of_Leads__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Leads__c</fullName>
    <formula>Account__r.Number_of_Leads__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Leads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Member of Multi-User Subscription</fullName>
            </value>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/UpdateContactsOnAccountTest.cls
@isTest
public class UpdateContactsOnAccountTest {

    static testmethod void UpdateLeadsOnAccountTest() {
        Account acct = new Account();
        acct.Name = 'test';
        insert acct;
        List<Lead> leads2 = new List<Lead>();
        for (integer x = 0; x < 2; x++) {
            Lead aLead = new Lead();
            aLead.lastName = 'Test2' + x;
            aLead.Company = 'TestComany2' + x;
            aLead.Account__c = acct.id;
            leads2.add(aLead);
        }
        insert leads2;
        
        Test.startTest();
        AccountRollupBatch arb = new AccountRollupBatch();
        Id batchId = Database.executeBatch(arb);
        Test.stopTest();
        
        Account acct1 = [select Number_Of_Contacts__c, Number_of_Singles_Users__c, Number_of_Leads__c from Account where id =: acct.id].get(0);
        System.assert(acct1.Number_of_Leads__c == 2);
    }


    static testmethod void UpdateContactsOnAccountTest() {
        Account acct = new Account();
        acct.Name = 'test';
        insert acct;
        List<Contact> cons = new List<Contact>();
        for (integer x = 0; x < 100; x++) {
            Contact aCon = new Contact();
            aCon.FirstName = 'Test1FName' + x;
            aCon.LastName = 'Test1LName' + x;
            aCon.AccountId = acct.id;
            aCon.User_Type__c = 'Single';
            aCon.Expiration_Date__c = System.today() +1;
            cons.add(aCon);
        }
        insert cons;
        
        
        Account acct2 = new Account();
        acct2.Name = 'test2';
        insert acct2;
        Contact aCon2 = new Contact();
        aCon2.FirstName = 'Test1FName2';
        aCon2.LastName = 'Test1LName2';
        aCon2.AccountId = acct2.id;
        aCon2.User_Type__c = 'Single2';
        insert aCon2;
        
        Test.startTest();
        AccountRollupBatch arb = new AccountRollupBatch();
        Id batchId = Database.executeBatch(arb);
        Test.stopTest();

        System.Debug('cons.size() = ' + cons.size());
        Account acct1 = [select Number_Of_Contacts__c, Number_of_Singles_Users__c, Number_of_Leads__c from Account where id =: acct.id].get(0);
        System.Debug('acct1.Number_Of_Contacts__c = ' + acct1.Number_Of_Contacts__c);
        System.assert(acct1.Number_Of_Contacts__c == 100);
        System.assert(acct1.Number_of_Singles_Users__c == 100);

    }


}