unpackaged/main/default/objects/Account/fields/Number_of_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Contacts__c</fullName>
    <description>Shows the number of Contacts associated with this Account.</description>
    <label>Number of Contacts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_of_Leads__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Leads__c</fullName>
    <description>Shows the number of Leads associated with this Account.</description>
    <label>Number of Leads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_of_Multi_Users__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Multi_Users__c</fullName>
    <description>Shows the number of Multi Subscription users associated with this Account.</description>
    <label>Number of Multi Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_of_Singles_Users__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Singles_Users__c</fullName>
    <description>Shows the number of Single Subscription users associated with this Account.</description>
    <label>Number of Singles Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Multi</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Member of Multi-User Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Number_of_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Contacts__c</fullName>
    <formula>Account__r.Number_of_Contacts__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Contacts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Number_of_Leads__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Leads__c</fullName>
    <formula>Account__r.Number_of_Leads__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Leads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Number_of_Multi_Users__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Multi_Users__c</fullName>
    <formula>Account__r.Number_of_Multi_Users__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Multi Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Member of Multi-User Subscription</fullName>
            </value>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/AccountRollupUtilityController.cls
public class AccountRollupUtilityController {
    List <Account> accts;
    Public Integer consUpdated {get;set;}
    Public Integer leadsUpdated {get;set;}
    
    public AccountRollupUtilityController() {
        consUpdated = 0;
        leadsUpdated = 0;
        accts = [select Id, Number_Of_Contacts__c, Number_of_Multi_Users__c, Number_of_Singles_Users__c from Account];
    }
    
    Public void rollupContacts () {
        List <Contact> cons = [select Id, AccountID, User_Type__c from Contact];
        Map<ID, List <Contact>> mapCons = new Map<ID, List <Contact>>();
        for(Account acct : accts) {
            List <Contact> acctCons = new List <Contact>();
            for (Contact aCon : cons) {
                if (aCon.AccountID == acct.Id) {
                    acctCons.add(aCon);
                }
            }
            mapCons.put(acct.id, acctCons);
        }
        for (Account acct : accts) {
            List <Contact> allAcctCons = mapCons.get(acct.Id);
            if (allAcctCons.size() > 0) {
                acct.Number_Of_Contacts__c = allAcctCons.size();
                if (acct.Number_of_Multi_Users__c == null) {
                    acct.Number_of_Multi_Users__c = 0;
                }
                if (acct.Number_of_Singles_Users__c == null) {
                    acct.Number_of_Singles_Users__c = 0;
                }
                integer iMultiCons = 0;
                integer iSingleCons = 0;
                for(Contact aConType : allAcctCons) {
                    if (aConType.User_Type__c != null && aConType.User_Type__c.contains('Multi')) {
                        iMultiCons++;
                    } else if (aConType.User_Type__c != null &&  aConType.User_Type__c == 'Single') {
                        iSingleCons++;
                    }
                }
                acct.Number_of_Multi_Users__c = iMultiCons;
                acct.Number_of_Singles_Users__c = iSingleCons;
                System.debug('iMultiCons = ' + iMultiCons);
                System.debug('iSingleCons = ' + iSingleCons);
                System.debug('Number of Contacts = ' + allAcctCons.size());
                consUpdated++;
            }
        }
        update accts;
    }

	Public void rollupLeads () {
        List <Lead> leads = [select Id, Account__c from Lead];
        Map<ID, List <Lead>> mapLeads = new Map<ID, List <Lead>>();
        for(Account acct : accts) {
            List <Lead> acctleads = new List <Lead>();
            for (Lead aLead : leads) {
                if (aLead.Account__C == acct.Id) {
                    acctleads.add(aLead);
                }
            }
            mapLeads.put(acct.id, acctleads);
        }
        for (Account acct : accts) {
            List <Lead> allAcctLeads = mapLeads.get(acct.Id);
			acct.Number_of_Leads__c = allAcctLeads.size();
            System.debug('Number of Leads = ' + allAcctLeads.size());
            leadsUpdated++;
        }
        update accts;
    }
    
}