unpackaged/main/default/objects/Account/fields/Number_of_Multi_Users__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Multi_Users__c</fullName>
    <description>Shows the number of Multi Subscription users associated with this Account.</description>
    <label>Number of Multi Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Number_of_Singles_Users__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Singles_Users__c</fullName>
    <description>Shows the number of Single Subscription users associated with this Account.</description>
    <label>Number of Singles Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <label>User Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Multi</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
            <value>
                <fullName>Member of Multi-User Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CalculateExpiredContacts.cls
public class CalculateExpiredContacts {
    
    public void updateAccounts() {
        List<Account> acctUpdateList = new List<Account>();
        List<Contact> expiredCons = [Select Id, AccountID, User_type__c from Contact where Expiration_Date__c =: System.today()];
        Map<ID, Contact> AcctIDMap = new Map<ID, Contact>();
        for (Contact aCon: expiredCons) {
            AcctIDMap.put(aCon.AccountID, aCon);
        }
        Map<ID, Account> acctsToUpdate = new Map<ID, Account>([select ID, Number_of_Multi_Users__c, Number_of_Singles_Users__c from Account where ID IN: AcctIDMap.keySet()]);
        for (Contact aCon: expiredCons) {
            Account acct = acctsToUpdate.get(aCon.AccountId);
            if (aCon.User_Type__c != null && aCon.User_Type__c.contains('Multi')) {
                acct.Number_of_Multi_Users__c = acct.Number_of_Multi_Users__c - 1;
            } else if (aCon.User_Type__c != null && aCon.User_Type__c == 'Single' ) {
                acct.Number_of_Singles_Users__c = acct.Number_of_Singles_Users__c - 1;
            }
        }
        
        for(ID acctID : acctsToUpdate.keySet()) {
            acctUpdateList.add(acctsToUpdate.get(acctID));
        }
        update acctUpdateList;
    }

}