unpackaged/main/default/objects/Contact/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <inlineHelpText>Expiration Date of current Subscription.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Renewal_Rate__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Rate__c</fullName>
    <label>Renewal Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Renewal_Rate__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Rate__c</fullName>
    <label>Renewal Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compliance Week</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Duration_Days__c.field-meta.xml
<CustomField>
    <fullName>Duration_Days__c</fullName>
    <label>Duration (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Subscription.recordType-meta.xml
<RecordType>
    <fullName>Subscription</fullName>
    <active>true</active>
    <description>Subscription based Products</description>
    <label>Subscription</label>
</RecordType>

unpackaged/main/default/objects/Quote/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

unpackaged/main/default/objects/User/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compliance Week</fullName>
            </value>
            <value>
                <fullName>NHiS</fullName>
            </value>
            <value>
                <fullName>Binley's</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TestVisualforceEmailController.cls
/**
 * Class to test VisualforceEmailController
 * @author : SUY Sreymol
 * @createddate : 13-Jan-2014
 */
 @isTest(SeeAllData=true)
public class TestVisualforceEmailController {
	private static User u;
	private static Opportunity opp;
	private static OpportunityLineItem oli;
	
	/**
	 * Set up data for testing
	 */
	static void setupdData() {
		String proId = [Select Id From Profile Where Name = 'System Administrator' limit 1].Id;
		u = new User(alias = 'u2', email = 'VisualforceEmailController@test.com', emailencodingkey = 'UTF-8', 
                            FirstName = 'VisualforceEmailController' , lastname = 'User', languagelocalekey = 'en_US',
                            localesidkey = 'en_US', profileid = proId, timezonesidkey = 'America/Los_Angeles', CommunityNickname = 'VE',
                            isActive = true, username = 'VisualforceEmailController@test.com');
        insert u;
        
        Account acc = new Account(Name = 'Account EV');
        insert acc;
        
    	Contact con = new Contact(AccountId = acc.Id, LastName = 'Contact VE', Email = 'sendemail@developer.com');
        insert con;
        
        Pricebook2 pb2Standard = new Pricebook2();
        if(TestOpportunityTrigger.mapPriceBook == null){
        	TestOpportunityTrigger.mapPriceBook = new Map<String,Pricebook2>();
        	pb2Standard = [Select p.IsStandard, p.Id From Pricebook2 p where IsStandard = true];
        	TestOpportunityTrigger.mapPriceBook.put('PriceBookKey',pb2Standard);
        }else if(TestOpportunityTrigger.mapPriceBook.containsKey('PriceBookKey')){ 
        	pb2Standard = TestOpportunityTrigger.mapPriceBook.get('PriceBookKey');
        }
            
        //PriceBook2 pb2Standard = [select Id from Pricebook2 where isStandard = true limit 1];
        
        RecordType rt = [Select r.SobjectType, r.Name, r.Id, r.DeveloperName From RecordType r Where SobjectType = 'Product2' and DeveloperName = 'Subscription' limit 1];
        Product2 p2 = new Product2(Name = 'Test Product', isActive = true, Family = 'Subscriptions', RecordTypeId = rt.Id,Duration_Days__c=30);
		insert p2;
		
		PricebookEntry pbe = new PricebookEntry(Pricebook2Id = pb2Standard.Id, Product2Id = p2.Id, UnitPrice = 99, isActive = true);
		insert pbe;
        
        opp = new Opportunity(Business_Unit__c ='Renewal', Name = 'Opp EV', OwnerId = u.Id, Pricebook2Id = pb2Standard.Id, StageName = 'Inquiry', Expiration_Date__c = system.today().addDays(10), CloseDate = system.today(), AccountId = acc.Id);
        insert opp;
        
		Quote q = new Quote(Name = 'testQuote ', OpportunityId = opp.Id, ContactId = con.Id, Pricebook2Id = pb2Standard.id);
        insert q ;
        
        QuoteLineItem quoteLine = new QuoteLineItem(QuoteId = q.Id, PricebookEntryId = pbe.Id ,UnitPrice = 100,Quantity = 1 ,ServiceDate = System.today());
        insert quoteLine;
        
        opp.SyncedQuoteId = q.Id;
        update opp;
        
        oli = new OpportunityLineItem(PriceBookEntryId = pbe.Id, OpportunityId = opp.Id, Quantity = 1, TotalPrice = 99, Contact__c = con.Id, Expiry_Date__c = system.today().addDays(10), ServiceDate = system.today(), Renewal_Rate__c = 10);
		insert oli;
		
	}
	
	/** 
	 * Test method
	 */ 
	
	static testmethod void testVisualforceEmailController() {
		
		setupdData();
        system.runAs(u) {
       		Test.startTest();
        		
        	
        		PageReference aPage = Page.VisualforceEmailPage;
        		aPage.getParameters().put('id', oli.Id);
        		// In case decline
        		aPage.getParameters().put('action', 'decline');
        		Test.setCurrentPage(aPage);
        		VisualforceEmailController controller = new VisualforceEmailController();
        		controller.updateOppAndCreateTask();
        		system.assertEquals(VisualforceEmailController.CLOSED_LOST_OPP, [select StageName From Opportunity Where Id = : opp.Id limit 1].StageName, 'If person clicks on decline, update Opportunity stage to Closed Lost.');
        		system.assertEquals(u.Id, [Select OwnerId From Task Where OwnerId =: opp.OwnerId].OwnerId, 'If person clicks on decline, create a task.');
        		// In case Accept
        		opp.StageName = 'Defaulted';
        		update opp;
        		aPage.getParameters().put('action', 'accept');
        		Test.setCurrentPage(aPage);
        		controller = new VisualforceEmailController();
        		controller.updateOppAndCreateTask();
        		system.assertEquals(VisualforceEmailController.CLOSED_WON_OPP, [select StageName From Opportunity Where Id = : opp.Id limit 1].StageName, 'If person clicks on decline, update Opportunity stage to Closed Won.');
        		system.assertEquals(1, [Select OwnerId From Task Where OwnerId =: opp.OwnerId].size(), 'If person clicks on accept, not create a task.');
        		// To test send email
        		VisualforceEmailController.sendMail(opp.Id);
        		//system.assertEquals(opp.Id,  [select WhatId from Task Where WhatId = : opp.Id].WhatId, 'After email have been send, create a task.');
        	Test.stopTest();
        }
	}
}