unpackaged/main/default/objects/Contact/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 year</fullName>
            </value>
            <value>
                <fullName>2 years</fullName>
            </value>
            <value>
                <fullName>3 years</fullName>
            </value>
            <value>
                <fullName>4 years</fullName>
            </value>
            <value>
                <fullName>5 years</fullName>
            </value>
            <value>
                <fullName>10 days</fullName>
            </value>
            <value>
                <fullName>30 days</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <inlineHelpText>Expiration Date of current Subscription.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Lost_Reason__c</fullName>
    <label>Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Lost on Price</fullName>
            </value>
            <value>
                <fullName>Lost to Competitor</fullName>
            </value>
            <value>
                <fullName>Low Usage</fullName>
            </value>
            <value>
                <fullName>No Longer in Role</fullName>
            </value>
            <value>
                <fullName>Service Not Required</fullName>
            </value>
            <value>
                <fullName>Company has Multi</fullName>
            </value>
            <value>
                <fullName>Renewal Opportunity Expired</fullName>
            </value>
            <value>
                <fullName>Declined Renewal</fullName>
            </value>
            <value>
                <fullName>Recapture Opportunity Expired</fullName>
            </value>
            <value>
                <fullName>Schedule Conflict</fullName>
            </value>
            <value>
                <fullName>Travel Freeze</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Not a Qualified Opportunity</fullName>
            </value>
            <value>
                <fullName>No Reply/No Response</fullName>
            </value>
            <value>
                <fullName>Opportunity Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Origination__c.field-meta.xml
<CustomField>
    <fullName>Origination__c</fullName>
    <description>Where the transaction came from.</description>
    <label>Origination</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cvent</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
                <default>true</default>
                <label>Website</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Renewal_Rate__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Rate__c</fullName>
    <label>Renewal Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Subscriptions_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Subscriptions_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Subscriptions</businessProcess>
    <label>Subscription Opportunity</label>
</RecordType>

unpackaged/main/default/objects/OpportunityLineItem/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>Expiry_Date__c - ServiceDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Renewal_Rate__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Rate__c</fullName>
    <label>Renewal Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>.Subscription generated when Opportunity is Closed Won.</inlineHelpText>
    <label>Subscription</label>
    <referenceTo>Subscription_NEW__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compliance Week</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Duration_Days__c.field-meta.xml
<CustomField>
    <fullName>Duration_Days__c</fullName>
    <label>Duration (Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Max_Users__c.field-meta.xml
<CustomField>
    <fullName>Max_Users__c</fullName>
    <label>Max. Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Min_Users__c.field-meta.xml
<CustomField>
    <fullName>Min_Users__c</fullName>
    <label>Min. Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Subscription.recordType-meta.xml
<RecordType>
    <fullName>Subscription</fullName>
    <active>true</active>
    <description>Subscription based Products</description>
    <label>Subscription</label>
</RecordType>

unpackaged/main/default/objects/Quote/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

unpackaged/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>A subscription to an edition of a publication.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>S-{000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Owner of this Subscription</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Subscription__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <defaultValue>Today()+365</defaultValue>
    <description>Date this subscription expires</description>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Subscription__c/fields/Renewal_Rate__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Rate at which this subscription renews</description>
    <label>Renewal Rate</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/Subscription_NEW__c.object-meta.xml
<CustomObject>
    <label>Subscription (NEW)</label>
    <nameField>
        <displayFormat>Sub-{0000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions (NEW)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Subscriptions (NEW)</relationshipLabel>
    <relationshipName>Subscriptions_NEW</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Minimum_Users__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Users__c</fullName>
    <label>Minimum Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Recapture_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Recapture_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If this Subscription does not renew, a recapture Opportunity is created 30 days after it expires.</inlineHelpText>
    <label>Recapture Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Subscriptions (NEW) (Recapture Opportunity)</relationshipLabel>
    <relationshipName>Subscriptions_New1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Recaptured__c.field-meta.xml
<CustomField>
    <fullName>Recaptured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recaptured</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Renewal_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A renewal Opportunity is created 90 days before this subscription expires. If upgraded mid-term via the button above, the upgrade Opportunity created is referenced here.</inlineHelpText>
    <label>Renewal/Upgrade Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Subscriptions (NEW)</relationshipLabel>
    <relationshipName>Subscriptions_NEW</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Renewal_Rate__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Rate__c</fullName>
    <label>Renewal Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Multi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TestOpportunityTrigger.cls
/**
 * Class to test trigger on opporunity to create Subscription_NEW__c for each product when an Opportunity is Closed Won and record type = 'Subscription'
 * Create date 31/12/2013
 */
@isTest(SeeAllData=true)
public class TestOpportunityTrigger {
    private static final String TYPE_SINGLE = 'Single';
    private static final String TYPE_MULTI = 'Multi';
    private static final String STAGE_CLOSEWON = 'Closed Won';
    private static final String FAMILY_SUBSCRIPTION = 'Subscriptions';
    private static final String RECORDTYPE_SUBSCRIPTION = 'Subscriptions_Opportunity';
    private static final String BUSINESSUNIT           = 'Compliance Week';
    private static final String STAGE_CLOSELOST        = 'Closed Lost';
    private static final String LOST_REASON            = 'Renewal Opportunity Expired';
    private static final String BUSINESSTYPE_RENEWAL   = 'Renewal';
    public static Map<String, Pricebook2> mapPriceBook ;
    static testMethod void myUnitTest() {
        Test.startTest();
            Account accRecord = new Account(Name = 'testAccount');
            insert accRecord;
            Product2 prod = new Product2(Name = 'testProduct', Min_Users__c = 1, Max_Users__c =1, Family = FAMILY_SUBSCRIPTION,Duration_Days__c = 90, IsActive = true);
            insert prod;
            Pricebook2 pb = new Pricebook2();
            if(mapPriceBook == null){
                mapPriceBook = new Map<String,Pricebook2>();
                pb = [Select p.IsStandard, p.Id From Pricebook2 p where IsStandard = true];
                mapPriceBook.put('PriceBookKey',pb);
            }else if(mapPriceBook.containsKey('PriceBookKey')){
                pb = mapPriceBook.get('PriceBookKey');
            }
            //Pricebook2 pb = [Select p.IsStandard, p.Id From Pricebook2 p where IsStandard = true];
            PricebookEntry pbe = new PricebookEntry(UnitPrice = 100,Pricebook2Id=pb.Id, Product2Id = prod.ID, IsActive = true);
            insert pbe;
            
            Contact con = new Contact(LastName = 'test', AccountId = accRecord.Id);
            insert con;
            
            RecordType reType = [select id from RecordType where DeveloperName =: RECORDTYPE_SUBSCRIPTION ];
            Opportunity opp = new Opportunity(Name = 'test Renewal 2013 Renewal', 
                                            StageName = 'Inquiry', 
                                            Probability = 100,
                                            RecordTypeId = reType.Id, 
                                            Origination__c = 'test',
                                            Lost_Reason__c = 'test',
                                            Duration__c = 'test',
                                            CloseDate = System.today()+7,
                                            Amount = 100,
                                            AccountId = accRecord.Id,
                                            Pricebook2Id = pb.Id,
                                            Business_Unit__c = 'test');
            insert opp;
            OpportunityLineItem oppLine = new OpportunityLineItem(UnitPrice = 100, Quantity = 1, PricebookEntryId = pbe.Id, OpportunityId = opp.Id, Contact__c = con.Id, ServiceDate=System.today());
            insert oppLine;
            Quote q = new Quote(Name = 'testQuote1', OpportunityId = opp.Id, ContactId = con.Id, Pricebook2Id = pb.id);
            insert q ;
            QuoteLineItem quoteLine = new QuoteLineItem(QuoteId = q.Id, PricebookEntryId = pbe.Id ,UnitPrice = 100,Quantity = 1 ,ServiceDate = System.today());
            insert quoteLine;
            //sync quote
            opp.SyncedQuoteId = q.Id;
            update opp;
            //set contact to oppline
            OpportunityLineItem oppLineSelect = [select Subscription__c, Expiry_Date__c , OpportunityId, Contact__c, ServiceDate from OpportunityLineItem where OpportunityId =: opp.Id limit 1];
            oppLineSelect.Contact__c = con.Id;
            oppLineSelect.Renewal_Rate__c = 100;
        	oppLineSelect.Expiry_Date__c = system.today() +100;
            update oppLineSelect;
            //udpate opportunity to close won
            opp.Business_Unit__c = BUSINESSUNIT;
            opp.StageName = STAGE_CLOSEWON;
            update opp;
        //assert for each opportunity product with subscription that just create
        Set<String> sSubId = new Set<String>();
        for(OpportunityLineItem oppLines : [select id,Expiry_Date__c,UnitPrice,Renewal_Rate__c, Contact__c,ServiceDate, Subscription__r.Start_Date__c, 
                        Subscription__r.Expiration_Date__c, Subscription__r.Contact__c, Subscription__r.Amount__c, Subscription__r.Renewal_Rate__c, Subscription__c
                        from OpportunityLineItem where OpportunityId =: opp.Id]){
            // System.assertEquals(System.today()+90, oppLines.Subscription__r.Expiration_Date__c);
           // System.assertEquals(oppLines.Contact__c, oppLines.Subscription__r.Contact__c);
            //System.assertEquals(oppLines.ServiceDate, oppLines.Subscription__r.Start_Date__c);
            //System.assertEquals(oppLines.UnitPrice, oppLines.Subscription__r.Amount__c);
           // System.assertEquals(oppLines.Renewal_Rate__c, oppLines.Subscription__r.Renewal_Rate__c);
            sSubId.add(oppLines.Subscription__c);
        }
        //generate renwal opp
      /*  BatchCloneOpportunity.cloneOpportunity(opp.Id);
        BatchCloneOpportunity.isBatchInProcess('BatchCloneOpportunity');
        test.stopTest();
        
        //select subscription after clone
        Subscription_NEW__c sub = [Select s.Renewal_Opportunity__c, s.Recaptured__c, Recapture_Opportunity__c,Renewal_Rate__c,Type__c ,Minimum_Users__c  From Subscription_NEW__c s where id IN: sSubId];
        // when renewal opp is close won
        Opportunity renewalOpp = [select id,StageName, Amount,CloseDate,Lost_Reason__c from Opportunity where id =: sub.Renewal_Opportunity__c];
        renewalOpp.StageName = STAGE_CLOSEWON;
        update renewalOpp;
        sub.Minimum_Users__c = 5;
        update sub;
        renewalOpp.StageName = STAGE_CLOSEWON;
        update renewalOpp;
        sub.Minimum_Users__c = 0;
        update sub;
        renewalOpp.StageName = STAGE_CLOSEWON;
        update renewalOpp;
        //when renewal opp is close lose => create recapture opp
        renewalOpp.StageName = STAGE_CLOSELOST;
        renewalOpp.Lost_Reason__c = LOST_REASON;
        update renewalOpp;
        //assert recapture opp name
        Subscription_NEW__c sub1 = [Select s.Renewal_Opportunity__c, s.Recaptured__c, Recapture_Opportunity__c,Renewal_Rate__c,Type__c ,Minimum_Users__c,Name  From Subscription_NEW__c s where id IN: sSubId];
        Opportunity recaptureOpp = [select id,StageName,Name from Opportunity where id =: sub1.Recapture_Opportunity__c];
        System.assertEquals('testAccount - '+sub1.Name+' - Recapture',recaptureOpp.Name);
        //when recapture opp is close won
        recaptureOpp.StageName = STAGE_CLOSEWON;
        update recaptureOpp;
        sub.Minimum_Users__c = 5;
        update sub;
        recaptureOpp.StageName = STAGE_CLOSEWON;
        update recaptureOpp;
        sub.Minimum_Users__c = 1;
        update sub;
        recaptureOpp.StageName = STAGE_CLOSEWON;
        update recaptureOpp;
        */
    } 
}