unpackaged/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Recapture</fullName>
            </value>
            <value>
                <fullName>Repeat Business</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
            <value>
                <fullName>Renewal Upgrade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <inlineHelpText>Expiration Date of current Subscription.</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Subscriptions_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Subscriptions_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Subscriptions</businessProcess>
    <label>Subscription Opportunity</label>
</RecordType>

unpackaged/main/default/objects/Quote/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

unpackaged/main/default/objects/Subscription_NEW__c/Subscription_NEW__c.object-meta.xml
<CustomObject>
    <label>Subscription (NEW)</label>
    <nameField>
        <displayFormat>Sub-{0000000}</displayFormat>
        <label>Subscription ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions (NEW)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Subscriptions (NEW)</relationshipLabel>
    <relationshipName>Subscriptions_NEW</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Renewal_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A renewal Opportunity is created 90 days before this subscription expires. If upgraded mid-term via the button above, the upgrade Opportunity created is referenced here.</inlineHelpText>
    <label>Renewal/Upgrade Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Subscriptions (NEW)</relationshipLabel>
    <relationshipName>Subscriptions_NEW</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Subscription_NEW__c/fields/Upgraded__c.field-meta.xml
<CustomField>
    <fullName>Upgraded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Upgraded</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/CreateUpgradeOpportunity.cls
global class CreateUpgradeOpportunity {
	public static final String SUBSCRIPTIONRECORDTYPE = 'Subscriptions_Opportunity';
	public static final String BUSINESSTYPE_RENEWAL   = 'Renewal';
	public static final String STAGE_PROPOSAL = 'Proposal/Price Quote';
	public static final String BUSINESSTYPE_UPGRADE   = 'Upgrade';
	public static final String BUSINESSUNIT           = 'Compliance Week';
	public static final String OPP_TYPE 			  = 'Subscription';
	webservice static String CreateUpgradeOpportunity(String id) {
		Subscription_NEW__c sub = [select id,Renewal_Opportunity__c,Name,Account__r.Name, Renewal_Opportunity__r.Business_Type__c,Expiration_Date__c from Subscription_NEW__c where id =: id];
		if((sub.Renewal_Opportunity__c != null && sub.Renewal_Opportunity__r.Business_Type__c != null && sub.Renewal_Opportunity__r.Business_Type__c.equalsIgnoreCase(BUSINESSTYPE_RENEWAL)) || (sub.Expiration_Date__c != null && sub.Expiration_Date__c <= System.today()+90)) return 'false';
		 RecordType recordType = [select id from RecordType where DeveloperName =: SUBSCRIPTIONRECORDTYPE];
		 Opportunity opp = new Opportunity(Name 			= sub.Account__r.Name+' - '+sub.Name+' - Upgrade', 
					 						RecordTypeId	= recordType.Id, 
					 						AccountId		= sub.Account__c, 
					 						Type			= OPP_TYPE, 
					 						Business_Type__c= BUSINESSTYPE_UPGRADE, 
					 						CloseDate		= System.today(),
					 						StageName 		= STAGE_PROPOSAL,
					 						Business_Unit__c= BUSINESSUNIT);
		 insert opp;
		 sub.Renewal_Opportunity__c = opp.Id;
		 //sub.Upgraded__c            = true;
		 update sub;
		 return opp.Id ;
	}
}